export const estilos = {
  contenedor: {
    minHeight: "100vh",
    background: "#ecf0f1",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "Arial",
  },
  card: {
    background: "white",
    width: "100%",
    maxWidth: "700px",
    padding: "40px",
    borderRadius: "10px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.1)",
  },
  form: { display: "flex", flexDirection: "column", gap: "25px" },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  grupo: { display: "flex", flexDirection: "column", gap: "5px" },
  label: { fontWeight: "bold", fontSize: "0.9rem", color: "#34495e" },
  input: {
    padding: "12px",
    border: "1px solid #bdc3c7",
    borderRadius: "5px",
    fontSize: "1rem",
  },
  boton: {
    padding: "15px",
    background: "#2980b9",
    color: "white",
    border: "none",
    borderRadius: "5px",
    fontWeight: "bold",
    fontSize: "1.1rem",
    cursor: "pointer",
    transition: "0.3s",
  },
};
