export const estilos = {
  page: {
    maxWidth: 1100,
    margin: "0 auto",
  },
  titulo: {
    margin: "0 0 6px",
    color: "#2c3e50",
    fontSize: "1.6rem",
  },
  subtitulo: {
    margin: "0 0 24px",
    color: "#7f8c8d",
    fontSize: "0.95rem",
  },
  card: {
    background: "white",
    borderRadius: 10,
    padding: 24,
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    marginBottom: 20,
  },
  infoBanner: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    flexWrap: "wrap",
    background: "#eaf4fb",
    border: "1px solid #aed6f1",
    borderRadius: 8,
    padding: "12px 20px",
    marginBottom: 20,
    fontSize: "0.95rem",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: 6,
    fontSize: "0.9rem",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: "1px solid #ddd",
    borderRadius: 6,
    fontSize: "0.95rem",
    boxSizing: "border-box",
    outline: "none",
    marginBottom: 0,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr",
    gap: 16,
  },
  tablaWrapper: {
    maxHeight: 420,
    overflowY: "auto",
    borderRadius: 6,
    border: "1px solid #eee",
  },
  tabla: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    padding: "10px 14px",
    background: "#f4f6f7",
    fontWeight: "bold",
    fontSize: "0.85rem",
    color: "#555",
    textAlign: "left",
    position: "sticky",
    top: 0,
    zIndex: 1,
    borderBottom: "2px solid #ddd",
  },
  td: {
    padding: "9px 14px",
    borderBottom: "1px solid #f0f0f0",
    fontSize: "0.9rem",
  },
  code: {
    background: "#f0f3f4",
    padding: "2px 8px",
    borderRadius: 4,
    fontFamily: "monospace",
  },
  btnPrimario: {
    padding: "10px 22px",
    background: "#2c3e50",
    color: "white",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.95rem",
  },
  btnSecundario: {
    padding: "10px 22px",
    background: "#ecf0f1",
    color: "#2c3e50",
    border: "1px solid #bdc3c7",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: "0.95rem",
  },
  btnPeligro: {
    padding: "8px 18px",
    background: "white",
    color: "#e74c3c",
    border: "1.5px solid #e74c3c",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.88rem",
  },
  btnElegir: {
    padding: "5px 14px",
    background: "#2980b9",
    color: "white",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: "0.82rem",
  },
  btnElegido: {
    padding: "5px 14px",
    background: "#27ae60",
    color: "white",
    border: "none",
    borderRadius: 4,
    cursor: "default",
    fontSize: "0.82rem",
  },
  badgeDefectuosa: {
    background: "#c0392b",
    color: "white",
    padding: "2px 10px",
    borderRadius: 12,
    fontSize: "0.8rem",
  },
  badgeEstandar: {
    background: "#27ae60",
    color: "white",
    padding: "2px 10px",
    borderRadius: 12,
    fontSize: "0.8rem",
  },
  badgeCaducidadProxima: {
    background: "#f39c12",
    color: "white",
    padding: "4px 10px",
    borderRadius: "999px",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  badgeModelo: {
    background: "#34495e",
    color: "white",
    padding: "4px 10px",
    borderRadius: "999px",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  fechaError: {
    color: "#e74c3c",
    fontSize: "0.8rem",
    marginTop: 4,
  },
};
