FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Exponemos el puerto de Vite (por defecto 5173)
EXPOSE 5173

# Arrancamos en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]